import { HeroConfig } from "@/types/hero";

export const PROTAGONIST_HERO: HeroConfig = {
  id: "hero_protagonist",
  name: "靈宵天尊",
  title: "穿越修士",
  quality: "靈",
  faction: "群雄",
  role: "主角",
  avatar: "⚔️",
  imagePath: "/assets/heroes/protagonist.webp",
  description: "意料之外穿越至三國亂世修仙界的少年修士，御劍自如，擅長誘敵布陣。",
  tacticalQuote: "「以身作餌，引雷入陣！」",
  baseStats: {
    hp: 120,
    maxHp: 120,
    atk: 25,
    def: 10,
    speed: 12,
    moveRange: 3,
    attackRange: 1,
  },
  skills: [
    {
      id: "skill_lure",
      name: "假逃誘敵",
      description: "主動拉開距離吸引敵方首領追擊，若場上有伏擊單位則觸發突襲！",
      icon: "🏃‍♂️",
      effectType: "AMBUSH_SNIPE",
    },
  ],
};

export const SUMMONABLE_HEROES: HeroConfig[] = [
  {
    id: "hero_huang_zhong",
    name: "黃忠",
    title: "神箭仙將",
    quality: "仙",
    faction: "蜀",
    role: "弓手",
    avatar: "🏹",
    imagePath: "/assets/heroes/huang_zhong.webp",
    description: "修仙蜀山老仙將，百步穿楊！置身草叢可進入「伏擊」形態，一箭爆頭敵首。",
    tacticalQuote: "「老夫寶弓一開，百里敵首皆為草木！」",
    baseStats: {
      hp: 100,
      maxHp: 100,
      atk: 45,
      def: 8,
      speed: 14,
      moveRange: 2,
      attackRange: 4,
    },
    skills: [
      {
        id: "skill_huangzhong_ambush",
        name: "猛將一箭",
        description: "草叢伏擊觸發！當敵人進入射程即射殺敵首，其餘劫匪大機率潰逃！",
        icon: "🎯",
        effectType: "AMBUSH_SNIPE",
      },
    ],
  },
  {
    id: "hero_xiahou_dun",
    name: "夏侯惇",
    title: "獨目戰神",
    quality: "仙",
    faction: "魏",
    role: "前鋒",
    avatar: "🛡️",
    imagePath: "/assets/heroes/xiahou_dun.webp",
    description: "魔魏鐵血戰將，身懷不滅魔軀。與主角相鄰時獲得「鐵血援護」強力減傷。",
    tacticalQuote: "「拔矢吞睛！區區劫匪焉敢當吾前鋒！」",
    baseStats: {
      hp: 180,
      maxHp: 180,
      atk: 30,
      def: 22,
      speed: 10,
      moveRange: 3,
      attackRange: 1,
    },
    skills: [
      {
        id: "skill_xiahou_guard",
        name: "鐵血援護",
        description: "與主角相鄰時自動提供 40% 傷害豁免與反擊加成，正面硬剛全滅強敵！",
        icon: "🔰",
        effectType: "GUARD_COVER",
      },
    ],
  },
  {
    id: "hero_zhao_yun",
    name: "趙雲",
    title: "龍膽槍仙",
    quality: "帝",
    faction: "蜀",
    role: "突騎",
    avatar: "⚡",
    imagePath: "/assets/heroes/zhao_yun.webp",
    description: "銀槍白馬常山趙子龍，修得紫霄龍膽道，擁有極高機動性與無視防禦突貫能力。",
    tacticalQuote: "「長槍所向，皆為寒芒！」",
    baseStats: {
      hp: 130,
      maxHp: 130,
      atk: 38,
      def: 14,
      speed: 18,
      moveRange: 4,
      attackRange: 1,
    },
    skills: [
      {
        id: "skill_zhaoyun_charge",
        name: "七進七出",
        description: "長程穿透敵陣，無視目標 50% 防禦力，並提升自身閃避率。",
        icon: "🗡️",
        effectType: "PIERCE_CHARGE",
      },
    ],
  },
  {
    id: "hero_guo_jia",
    name: "郭嘉",
    title: "鬼才仙謀",
    quality: "帝",
    faction: "魏",
    role: "軍師",
    avatar: "📜",
    imagePath: "/assets/heroes/guo_jia.webp",
    description: "算無遺策的洞冥魔謀，通曉玄冰符陣，能遠程冰封敵方行動力。",
    tacticalQuote: "「算盡天機，勝負皆在吾一念之間。」",
    baseStats: {
      hp: 90,
      maxHp: 90,
      atk: 42,
      def: 6,
      speed: 11,
      moveRange: 2,
      attackRange: 3,
    },
    skills: [
      {
        id: "skill_guojia_freeze",
        name: "奇謀禁錮",
        description: "對範圍敵人施放冰心陣，造成法術傷害並使其無法移動 1 回合。",
        icon: "❄️",
        effectType: "FREEZE_CONTROL",
      },
    ],
  },
];

export const ENEMY_BANDIT_CHIEF: HeroConfig = {
  id: "enemy_bandit_chief",
  name: "獨眼寨主",
  title: "劫匪首領",
  quality: "靈",
  faction: "群雄",
  role: "前鋒",
  avatar: "👹",
  imagePath: "/assets/heroes/bandit_chief.webp",
  description: "攔路劫財的魔道散修，盤踞山頭為非作歹。",
  tacticalQuote: "「此山是我開！留下修仙資源饒爾不死！」",
  baseStats: {
    hp: 150,
    maxHp: 150,
    atk: 22,
    def: 12,
    speed: 11,
    moveRange: 3,
    attackRange: 1,
  },
  skills: [],
};

export const ENEMY_BANDIT_THUG: HeroConfig = {
  id: "enemy_bandit_thug",
  name: "黑風嘍囉",
  title: "山寨嘍囉",
  quality: "凡",
  faction: "群雄",
  role: "前鋒",
  avatar: "🧌",
  imagePath: "/assets/heroes/bandit_thug.webp",
  description: "依附黑風寨的小劫匪，欺軟怕硬。",
  tacticalQuote: "「老大衝啊！」",
  baseStats: {
    hp: 60,
    maxHp: 60,
    atk: 14,
    def: 5,
    speed: 9,
    moveRange: 2,
    attackRange: 1,
  },
  skills: [],
};
